- name: "configure {{ component }}"
  become: yes
  hosts: "{{ component }}"
  hosts: localhost
  roles: # this will automatically load a folder called roles in current working directory.
  - "{{ component }}"
