- name: Copy catalogue.service file
  ansible.builtin.template:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service

- name: Daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Start catalogue
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes